apiVersion: v1
kind: Service
metadata:
  name: hello-aspnetcore-service
spec:
  selector:
    app: hello-aspnetcore-pod #pod name in deployment.yml file
  ports:
  - port: 8080 #8080 port redirect to 80 port
    targetPort: 80 #container port in dockerfile
  type: LoadBalancer
